### ISSUE TITLE
Invalid face reference: quote

### ISSUE THREAD

**Issue by swarnendubiswas** [juan-leon/dired-efap#1]
I see this error while loading dired-efap with use-package. 

Loading package dired-efap...
Invalid face reference: quote [2 times]
Configuring package dired-efap...done

Here is my snippet:

  (use-package dired-efap
    :ensure t
    :config
    (setq dired-efap-initial-filename-selection nil) ; options: t, nil, no-extension
    (bind-key "<f2>" #'dired-efap dired-mode-map))

Perhaps there is an issue in defining dired-efap-face?

**Comment by marcel-becker** [comment]
;; This seems to solve the problem
;; Replace the original face definition in dired-efap.el:
(defface dired-efap-face
  (if (>= emacs-major-version 21)
      '((((supports '(:box t)) (background dark))
         (:box (:line-width 2 :color "white" :style pressed-button)))
        (((supports '(:box t)) (background light))
         (:box (:line-width 2 :color "black" :style pressed-button)))
        (t (:inverse-video t)))
    '((t (:inverse-video t))))
  "Face used for filenames being edited."
  :group 'dired-efap)

;; with (remove the single quote before (:box t)
(defface dired-efap-face
  (if (>= emacs-major-version 21)
      '((((supports (:box t)) (background dark))
         (:box (:line-width 2 :color "white" :style pressed-button)))
        (((supports (:box t)) (background light))
         (:box (:line-width 2 :color "black" :style pressed-button)))
        (t (:inverse-video t)))
    '((t (:inverse-video t))))
  "Face used for filenames being edited."
  :group 'dired-efap)

**Comment by juan-leon** [comment]
Thanks for the info.

This is weird... both options work for me (the old and the proposed change).

The quoted version worked for every emacs version that I used (and since I use emacs-snapshot, I used them all)

What is the version and system where the quoted version is failing to work?

Thanks

**Comment by marcel-becker** [comment]
I am using emacs version 29.0.50. I build from emacs from HEAD on MacOs 12.3.1. 
The quoted version does not break anything, it just issues the warning but nothing breaks. 
Once I evaluate the defface construct in an emacs buffer, I see the message in the *Messages* buffer.

**Comment by juan-leon** [comment]
Thanks for the explanation (and for the fix).

I just pushed the fix with your suggested solution.
