### ISSUE TITLE
pressing del deletes all the way to start of line

### ISSUE THREAD

**Issue by zeltak** [juan-leon/dired-efap#2]
Hi!

i really love this package but i have several bugs. the most annoying is that when i issue dired-efap and go to the middle of a word and press del or backspace it  deletes all the way to start of line

is that normal or a bug?

best

Z

**Comment by juan-leon** [comment]
I think this is expected if you are using both `transient-mark-mode` (the default in emacs) _and_ `delete-selection-mode`.

If you do not like that you can set the variable `dired-efap-initial-filename-selection` to nil.  Either

```
M-x customize-variable dired-efap-initial-filename-selection
```

or in your init file

```
(setq dired-efap-initial-filename-selection nil)
```

I hope that helps.

**Comment by zeltak** [comment]
thx perfect!
really love this tiny (but big) enhancer to dired :)
best

z
